# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 80, 240, 50))
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 160, 240, 50))
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 240, 240, 50))
        self.pushButton_7.setObjectName("pushButton_7")

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(550, 520, 240, 50))
        self.pushButton_3.setObjectName("main_pushButton_3")

        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 320, 240, 50))
        self.pushButton_6.setObjectName("main_pushButton_6")

        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 0, 130, 25))
        self.pushButton_4.setObjectName("main_pushButton_4")

        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(300, 30, 240, 50))
        self.pushButton_8.setObjectName("pushButton_8")

        # self.label = QtWidgets.QLabel(MainWindow)
        # self.label.setGeometry(QtCore.QRect(260, 0, 90, 17))
        # self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(MainWindow)
        self.label_2.setGeometry(QtCore.QRect(300, 80, 450, 20))
        self.label_2.setObjectName("main_label_2")

        self.label_3 = QtWidgets.QLabel(MainWindow)
        self.label_3.setGeometry(QtCore.QRect(300, 110, 450, 20))
        self.label_3.setObjectName("main_label_3")

        self.label_4 = QtWidgets.QLabel(MainWindow)
        self.label_4.setGeometry(QtCore.QRect(300, 140, 450, 20))
        self.label_4.setObjectName("main_label_4")

        self.label_5 = QtWidgets.QLabel(MainWindow)
        self.label_5.setGeometry(QtCore.QRect(300, 170, 450, 20))
        self.label_5.setObjectName("main_label_5")

        self.label_7 = QtWidgets.QLabel(MainWindow)
        self.label_7.setGeometry(QtCore.QRect(300, 200, 450, 20))
        self.label_7.setObjectName("main_label_5")

        self.label_6 = QtWidgets.QLabel(MainWindow)
        self.label_6.setGeometry(QtCore.QRect(300, 230, 450, 190))
        self.label_6.setObjectName("label_6")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Лабораторная работа"))
        self.pushButton.setText(_translate("MainWindow", "Теория"))
        self.pushButton_2.setText(_translate("MainWindow", "Тест"))
        self.pushButton_3.setText(_translate("MainWindow", "Выход"))
        self.pushButton_4.setText(_translate("MainWindow", "Справка"))
        self.pushButton_6.setText(_translate("MainWindow", "Видеоматериалы"))
        self.pushButton_7.setText(_translate("MainWindow", "Практическое задание"))
        self.action.setText(_translate("MainWindow", "Помощь"))

        #self.label.setText(_translate("Dialog", "TextLabel"))
        self.label_2.setText(_translate("Dialog", "TextLabel"))
        self.label_3.setText(_translate("Dialog", "TextLabel"))
        self.label_4.setText(_translate("Dialog", "TextLabel"))
        self.label_5.setText(_translate("Dialog", "TextLabel"))
        self.label_6.setText(_translate("Dialog", "TextLabel"))
        self.label_7.setText(_translate("Dialog", "TextLabel"))