# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secondwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 600)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(500, 30, 700, 500))
        self.label.setObjectName("label")
        self.label.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(865, 550, 110, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(625, 550, 110, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(765, 550, 90, 17))
        self.label_2.setObjectName("label_2")

        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(5, 0, 390, 140))
        self.pushButton_3.setObjectName("1")

        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(5, 150, 390, 140))
        self.pushButton_4.setObjectName("2")

        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(5, 300, 390, 140))
        self.pushButton_5.setObjectName("3")

        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(5, 450, 390, 140))
        self.pushButton_6.setObjectName("4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "TextLabel"))
        self.pushButton.setText(_translate("Dialog", "Следующая"))
        self.pushButton_2.setText(_translate("Dialog", "Предыдущая"))
        self.label_2.setText(_translate("Dialog", "TextLabel"))

        self.pushButton_3.setText(_translate("Dialog", "Интегральные счетчики"))
        self.pushButton_4.setText(_translate("Dialog", "Суммирующий счетчик"))
        self.pushButton_5.setText(_translate("Dialog", "Счетчики (вычитающий,\n реверсивный, параллельный)"))
        self.pushButton_6.setText(_translate("Dialog", "Триггеры"))
